### ISSUE TITLE
If you have to big ftl types get to complex for ts compiler

### ISSUE THREAD

**Issue by LokiMidgard** [macabeus/fluent-typescript#15]
When I have over 50 entrys in the ftl file I get following error
```
TS2589: Type instantiation is excessively deep and possibly infinite.
```

it is also not trivial to split the translations on multiple d.ts files.

**Comment by macabeus** [comment]
Thank you to open this issue 😄
I haven't tested it on a large FTL file. Trying now, I get this error when I have at least 47 messages, without any placeable and using the vanilla output.

Maybe it could be fixed using overrides. Let's say: we have 50 messages, so split into two `PatternArguments`, each one with 25 messages. And we'll have two `formatPattern`, each one using one of that.
I don't know if I'll have time to fix that soon. But I would be happy if you could help to fix that.

**Comment by LokiMidgard** [comment]
I tried to test something out. I created a pull request so you can look at it.

I haven't any experience in building node tools so the code is a little bit ugly. I did not know how to get the output of the example vanila project, so I don't know if my changes actually work. But at least thy compile and the code looks like I would expect ;)

**Comment by macabeus** [comment]
No problem. I just finished to review your PR. Thank you =]

**Comment by macabeus** [comment]
Fixed: https://github.com/macabeus/fluent-typescript/pull/16
