### ISSUE TITLE
messages don't get delete in d.ts file if deleted in source ftl

### ISSUE THREAD

**Issue by LokiMidgard** [macabeus/fluent-typescript#17]
As mentioned in #16 removing a message from an `.ftl` file will not remove it from the `d.ts` file.

The tests check against this and pass. I found out that it sometimes works and sometimes not. More precisely:
  1. Adding a message -> message appears in `d.ts` file *(as expected)*
  2. Removing an just added message -> message vanishes from the `d.ts` file *(as expected)*
  3. Removing a message that was in the `.ftl` file before the process was started -> message will not be remover (I think that's an error)

The problem is that the path of the files differ betweein initial and update. Seems like a Windows only problem.

On input the path is 
```
assets/locales/jp/translations.ftl
```

On update
```
assets\locales\jp\translations.ftl
```

**Comment by LokiMidgard** [comment]
I tried to resolve this using [path.normalize](https://millermedeiros.github.io/mdoc/examples/node_api/doc/path.html#path.normalize) but adding path to the `package.json` and adding the import `import * as path from 'path'` compiles but results in an runtime error that path.normalize is undefined

**Comment by macabeus** [comment]
@LokiMidgard If you could open a PR, I can help better. Don't worry to open a broke PR. It's okay.
Since the PR https://github.com/macabeus/fluent-typescript/pull/16 was merged with many changes on codebase, I recommend to checkout on master and make your changes again (or merge your branch with master).

**Comment by LokiMidgard** [comment]
I opened #18 hope you find whats wrong.

**Comment by macabeus** [comment]
Done
