### ISSUE TITLE
When a file is deleted, should update the type as well

### ISSUE THREAD

**Issue by macabeus** [macabeus/fluent-typescript#19]
If we have:
```
# assets/locales/jp/translations.ftl
hello = こんにちは{ $lastName }
how-are-you = お元気ですか？
bye = じゃあね
```

```
# assets/locales/pt-br/translations.ftl
hello = Olá { $firstName }
how-are-you = Como você está?
bye = Tchau
foo = foo
```

The type definition file will have the types for all 4 messages - that is correct.

But if we remove the `pt-br/translations.ftl` file while running `fluent-typescript`, now we should have only the types for the 3 messages that still there are on our ftl files (removing `foo` that was existing only on `pt-br` version) - but it isn't happing. We should fix this behaviour.

**Comment by macabeus** [comment]
@LokiMidgard Maybe you would like to fix this bug.
There is the event [`unlink` on `chokidar`](https://github.com/paulmillr/chokidar#methods--events) to check when a file is removed, that could help you (will be necessary to check if this event or the event `unlinkDir` also will works when removing the folder `pt-br`).

Probably will be necessary to create a new event on `updateGlobalState` function, something like `{ type: 'removeContent', path: string }`.

**Comment by LokiMidgard** [comment]
It don't look like much work, but I won't be able to look into it this week, and probably not next week either but maybe I can fit it somewhere in.
