### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by LokiMidgard** [macabeus/fluent-typescript#22]
Hi @macabeus 

Any chance of releasing a new version to npm?
If I saw it correctly the fix for to many resources was included after the last release.

I currently have this project cloned as a submodule, but npm is not so reliable with local dependency pathes.
If I could switch back to the npm version this would make our builds more reliable.

**Comment by macabeus** [comment]
I didn't launch the new version because I was hoping to launch it with [this fix](https://github.com/macabeus/fluent-typescript/issues/19) too.
But okay, I can launch a new one today. I'll to do it today later.

**Comment by macabeus** [comment]
@LokiMidgard I just release the new version on NPM. Please, let me know if everything is working fine.

**Comment by LokiMidgard** [comment]
Sorry I totally forgot this. 😔

I have made a pullrequest for this now.

Oh and by the way your released version worked ;)
