### ISSUE TITLE
Under what license is this code project?

### ISSUE THREAD

**Issue by LokiMidgard** [macabeus/fluent-typescript#25]
I would like to use it in a project on work. But for that I need to know if it is under a compatible license.

**Comment by macabeus** [comment]
MIT: https://github.com/macabeus/fluent-typescript/blob/b6a523549077df23cc836b4013218da2da032ff4/package.json#L14

So probably you can use it on your work.

**Comment by LokiMidgard** [comment]
Ah thanks. I searched for a license file.
